version: "3"
services:

  jupyter:
    build:
      context: ./
    ports:
      - "8888:8888"
      - "4040:4040"
    environment:
      - GRANT_SUDO="yes"
    volumes:
#          - /Users/anelka/PycharmProjects/datascience:/notebooks
      - /Users/administrator/datascience/datascience:/notebooks